// Embedded detector file arrays — generated by build.rs into OUT_DIR.
// Included here so they are accessible as pub(crate) statics.
include!(concat!(env!("OUT_DIR"), "/embedded_file_arrays.rs"));

/// Access embedded tree-sitter query pack files (.scm).
pub(crate) struct EmbeddedTreeSitterQueries;

impl EmbeddedTreeSitterQueries {
    /// Return the content of a query pack file by name (e.g. "rust.scm").
    pub fn get(name: &str) -> Option<&'static str> {
        TREE_SITTER_QUERY_FILES
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, content)| *content)
    }

    /// Iterate the names of all embedded query pack files.
    pub fn iter() -> impl Iterator<Item = &'static str> {
        TREE_SITTER_QUERY_FILES.iter().map(|(name, _)| *name)
    }
}

/// Access embedded semgrep rule files (.yml).
pub(crate) struct EmbeddedSemgrepRules;

impl EmbeddedSemgrepRules {
    /// Return the bytes of a semgrep rule file by relative path
    /// (e.g. "api/rest_endpoints.yml").
    pub fn get(name: &str) -> Option<&'static [u8]> {
        SEMGREP_RULE_FILES
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, data)| *data)
    }

    /// Iterate the relative paths of all embedded semgrep rule files.
    pub fn iter() -> impl Iterator<Item = &'static str> {
        SEMGREP_RULE_FILES.iter().map(|(name, _)| *name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_tree_sitter_queries_are_present() {
        assert!(EmbeddedTreeSitterQueries::iter().count() > 0);
    }

    #[test]
    fn embedded_semgrep_rules_are_present() {
        assert!(EmbeddedSemgrepRules::iter().count() > 0);
    }

    #[test]
    fn tree_sitter_get_returns_some_for_known_file() {
        let first = EmbeddedTreeSitterQueries::iter().next().unwrap();
        assert!(EmbeddedTreeSitterQueries::get(first).is_some());
    }

    #[test]
    fn tree_sitter_get_returns_none_for_unknown_file() {
        assert!(EmbeddedTreeSitterQueries::get("nonexistent.scm").is_none());
    }

    #[test]
    fn semgrep_get_returns_some_for_known_file() {
        let first = EmbeddedSemgrepRules::iter().next().unwrap();
        assert!(EmbeddedSemgrepRules::get(first).is_some());
    }

    #[test]
    fn semgrep_get_returns_none_for_unknown_file() {
        assert!(EmbeddedSemgrepRules::get("nonexistent.yml").is_none());
    }

    #[test]
    fn all_tree_sitter_files_accessible() {
        for name in EmbeddedTreeSitterQueries::iter() {
            assert!(EmbeddedTreeSitterQueries::get(name).is_some());
        }
    }

    #[test]
    fn all_semgrep_files_accessible() {
        for name in EmbeddedSemgrepRules::iter() {
            assert!(EmbeddedSemgrepRules::get(name).is_some());
        }
    }
}
